/**
 * Deterministic TypeScript emitters for the generated data files. Output
 * depends only on the input values (no timestamps), so regenerating from
 * unchanged upstream data produces no diff.
 */

import type { Card, LevelLimits, TaxonomyRow } from "../../src/engine/types.ts";

const HEADER = (generator: string): string =>
  `// Generated by ${generator} from https://github.com/vertesan/gakumasu-diff — DO NOT EDIT.\n// Regenerate with \`bun run generate\`.\n`;

export function emitCards(cards: readonly Card[]): string {
  const lines = cards.map((c) => `  ${JSON.stringify(c)},`);
  return `${HEADER("scripts/generate-cards.ts")}import type { Card } from "../src/engine/types.ts";\n\nexport const CARDS: readonly Card[] = [\n${lines.join("\n")}\n];\n`;
}

export function emitLevelLimits(limits: LevelLimits): string {
  return `${HEADER("scripts/generate-cards.ts")}import type { LevelLimits } from "../src/engine/types.ts";\n\nexport const LEVEL_LIMITS: LevelLimits = ${JSON.stringify(limits, null, 2)};\n`;
}

export function emitTaxonomy(rows: readonly TaxonomyRow[]): string {
  const lines = rows.map((r) => `  ${JSON.stringify(r)},`);
  return `${HEADER("scripts/generate-taxonomy.ts")}import type { TaxonomyRow } from "../src/engine/types.ts";\n\nexport const TAXONOMY: readonly TaxonomyRow[] = [\n${lines.join("\n")}\n];\n`;
}
