// Generated by scripts/generate-cards.ts from https://github.com/vertesan/gakumasu-diff — DO NOT EDIT.
// Regenerate with `bun run generate`.
import type { HeldCard } from "../src/engine/types.ts";

/** Cards the table must not show: one of their effects cannot be counted (docs/adr/0005). Empty when every effect can. */
export const HELD: readonly HeldCard[] = [
];
