// Generated by scripts/generate-cards.ts from https://github.com/vertesan/gakumasu-diff — DO NOT EDIT.
// Regenerate with `bun run generate`.
import type { LevelLimits } from "../src/engine/types.ts";

export const LEVEL_LIMITS: LevelLimits = {
  "r": [
    20,
    25,
    30,
    35,
    40
  ],
  "sr": [
    30,
    35,
    40,
    45,
    50
  ],
  "ssr": [
    40,
    45,
    50,
    55,
    60
  ]
};
